# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true //Remove this line or it will deprecate the lastest version of Jekyll theme.

# Setup
title:               Ting's Square
tagline:             '程式寫作之路'
description:         '@tingtingtour 2018-2019 My Ruby on Rails Project'
url:                 https://github.com/tingtinghsu
baseurl:             '/blog'
excerpt_separator:  '<!-- more -->'

# About/contact
author:
  name:              Ting Ting Hsu
  url:               https://tingtinghsu.github.io/blog/
  email:             tingtinghsu.tw[at]gm

# Handling reading
encoding: "utf-8"

# Custom vars
version:             1.0.0
plugins: [jekyll-paginate]
paginate:           10
paginate_path:      "page:num"

# Social links
github_username:      tingtinghsu
twitter_username:     tingtingtour
wordpress_username:   tingtingtour
instagram_username:   tingtingtour

# Conversation
markdown: kramdown
highligher: rouge
excerpt_separator: "\n\n"

# Markdown processors
kramdown:
  toc_levels: 1..6
  auto_ids:     true
  footnote_nr:  1
  input: GFM
  entity_output: as_char
  hard_wrap: false

# Tag: generate pages for each tag where we can list posts
collections:
  tag:
    output: true

defaults:
  -
    scope:
      path: ""
      type: tag
    values:
      layout: "tag"

# Comments:
# comments :
#   provider : disqus    # default
#   disqus :
#     short_name : tingtingtour    # disqus site name
disqus:
  shortname: tingtingtour
#RSS settings
rss: true